#%RAML 1.0 Trait


  queryParameters:    
    since:
      description: Specify number of seconds to retrieve only delta records that have changed since the specified time period
      type: integer
      required: false
      example: 300



    