#%RAML 1.0 Trait


  queryParameters:    
    fields:
      description: Specify the fields needed for partial response as comma delimited values
      type: string
      required: false
      example: firstName,LastName
      