#%RAML 1.0 Trait


queryParameters: 
  search:
    description: Specify the search query to limit return records based on search criteria
    type: string
    required: false
    example: firstName:John+lastName:Doe
