#%RAML 1.0 NamedExample
value:
  -
    customerID: a-1234
    firstName: John
    lastName: Doe
    address: 
      addressLine1: "My Street"
      addressLine2: My Suburb
      city: Sydney
      state: NSW
      zipCode: 8888
      country: Australia
    customerType: X
  -
    customerID: b-5678
    firstName: Tim
    lastName: Mason
    address: 
      addressLine1: "My Street"
      addressLine2: My Suburb
      city: Sydney
      state: NSW
      zipCode: 8888
      country: Australia
    customerType: Y
