#%RAML 1.0 NamedExample

    firstName: John
    lastName: Doe
    address: 
      addressLine1: "My Street"
      addressLine2: My Suburb
      city: Sydney
      state: NSW
      zipCode: 8888
      country: Australia
    customerType: X
